# Generated by Django 3.1.3 on 2020-11-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.CharField(blank=True, max_length=2500, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_tel', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_link_facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('social_link_twitter', models.CharField(blank=True, max_length=1000, null=True)),
                ('social_link_instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('session_timeout', models.IntegerField(default=60, help_text='Session Timeout (Minutes)')),
                ('site', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.site')),
            ],
        ),
    ]
