# Generated by Django 3.1.3 on 2020-11-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='about',
            new_name='about_ENG',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='tagline',
            new_name='tagline_ENG',
        ),
        migrations.AddField(
            model_name='setting',
            name='about_POR',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='tagline_POR',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
