# Generated by Django 3.1.3 on 2020-12-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('common', '0003_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
    ]
