# Generated by Django 3.1.3 on 2020-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20201201_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='name',
        ),
        migrations.AddField(
            model_name='link',
            name='name_ENG',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Name (English)'),
        ),
        migrations.AddField(
            model_name='link',
            name='name_POR',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Name (Portuguese)'),
        ),
    ]
