# Generated by Django 3.1.3 on 2020-12-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20201201_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['id']},
        ),
    ]
