# Generated by Django 3.1.3 on 2020-11-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_num', models.IntegerField()),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('ALLOCATED', 'Allocated'), ('COMPLETED', 'Completed')], default='FREE', max_length=15)),
                ('participant', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactme', models.BooleanField()),
                ('withdraw', models.BooleanField()),
                ('replica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='studies.replica')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField()),
                ('tasktype', models.CharField(max_length=4)),
                ('oracle', models.IntegerField()),
                ('response', models.IntegerField(blank=True, null=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('finish', models.TimeField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scripts.script')),
            ],
            options={
                'order_with_respect_to': 'script',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_num', models.IntegerField()),
                ('tasktype', models.CharField(max_length=4)),
                ('value', models.CharField(max_length=100)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='scripts.step')),
            ],
            options={
                'order_with_respect_to': 'step',
            },
        ),
    ]
