# Generated by Django 3.1.3 on 2020-11-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20201117_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['step__script__replica__entrypoint', 'step__script__script_num', 'step__step_num', 'slot_num']},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['replica__entrypoint', 'script_num']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['script__replica__entrypoint', 'script__script_num', 'step_num']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='component',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='script',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='step',
            order_with_respect_to=None,
        ),
    ]
