# Generated by Django 3.1.3 on 2020-11-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_auto_20201119_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='finish',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='start',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
