# Generated by Django 3.1.3 on 2020-11-22 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_interestedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
