# Generated by Django 3.1.3 on 2020-11-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_script_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='unique_id',
            new_name='script_uuid',
        ),
    ]
