# Generated by Django 3.1.3 on 2020-11-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_auto_20201122_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='script_uuid',
        ),
    ]
