# Generated by Django 3.1.3 on 2020-11-22 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_remove_script_script_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
