# Generated by Django 3.1.3 on 2020-11-16 21:19

import common.storage
from django.db import migrations, models
import django.db.models.deletion
import studies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('object', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('objective', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Studies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Replica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrypoint', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('EN', 'English'), ('PT', 'Portuguese')], default='PT', max_length=2)),
                ('proponent', models.CharField(max_length=100)),
                ('sponsor', models.CharField(max_length=100)),
                ('approval', models.CharField(max_length=100)),
                ('consent', models.TextField()),
                ('invitation', models.TextField(blank=True, null=True)),
                ('thanks', models.TextField()),
                ('redirect', models.TextField()),
                ('close', models.TextField()),
                ('githubtag', models.CharField(blank=True, max_length=20, null=True)),
                ('objective', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('INACTIVE', 'In-active'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('COMPLETED', 'Completed')], default='INACTIVE', max_length=15)),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('candidates', models.IntegerField(blank=True, null=True)),
                ('participants', models.IntegerField(blank=True, null=True)),
                ('numtasks', models.IntegerField(blank=True, null=True)),
                ('numimages', models.IntegerField(blank=True, null=True)),
                ('activated', models.DateTimeField(blank=True, null=True)),
                ('deactivated', models.DateTimeField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='studies.study')),
            ],
            options={
                'ordering': ['entrypoint'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('content', models.ImageField(storage=common.storage.OverwriteStorage(), upload_to=studies.models.replicaImageSavePath)),
                ('replica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='studies.replica')),
            ],
        ),
    ]
