# Generated by Django 3.1.3 on 2020-11-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20201117_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['filename']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='image',
            order_with_respect_to=None,
        ),
    ]
