# Generated by Django 3.1.3 on 2020-11-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20201118_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['replica__entrypoint', 'filename']},
        ),
    ]
