# Generated by Django 3.1.3 on 2020-11-22 12:22

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_replica_save_uncompleted_scripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replica',
            name='entrypoint',
            field=models.CharField(editable=False, max_length=50, unique=True, validators=[common.utils.UnicodeEntrypointValidator()]),
        ),
    ]
