# Generated by Django 3.1.3 on 2020-11-22 13:16

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_auto_20201122_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replica',
            name='entrypoint',
            field=models.CharField(max_length=50, unique=True, validators=[common.utils.UnicodeEntrypointValidator()]),
        ),
    ]
