# Generated by Django 3.1.3 on 2020-11-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_auto_20201122_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replica',
            old_name='deactivated',
            new_name='completed',
        ),
        migrations.AlterField(
            model_name='replica',
            name='approval',
            field=models.CharField(max_length=150),
        ),
    ]
