# Generated by Django 3.1.3 on 2020-11-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_auto_20201123_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replica',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('COMPLETED', 'Completed')], default='INACTIVE', max_length=15),
        ),
    ]
